#pragma config(Sensor, dgtl1,  btn,            sensorTouch)
#pragma config(Motor,  port1,           DTR,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          DTR,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int mode = 1
	while (true)
	{
		//if (vexRT[Btn8U] == 1)
		//SELFAWARE.LUA
		//e2function number changed(value)
		//	local chg = self.data.changed

		//	if value == chg[args] then return 0 end

		//	chg[args] = value
		//	return 1
		//end

		if (sensorValue(btn) == 1)
		{
			mode = 1 - mode;
		}
		displayLCDNumber(1, 1, mode, 5);
	}
}
